openapi: 3.0.0
info:
  title: p1ComputeAirInterfaceNames
  version: 1.0.0

x-javascript-interface:
  p1ComputeAirInterfaceNames: 
    summary: 'This function provides the AirInterface names looked up from LtpAugment information'
    input:
      required: true
      content:
        application/json:
          schema:
            oneOf:
              - description: 'data reference'
                type: object
                properties:
                  _control-construct:
                    type: object
                    description: >
                      'The reference to the Control-Construct object on which lookup shall be executed.
                      The data follows ONF schema. Option LtpStructureAndAugment lists the relevant attributes and subclasses.'
                  uuid:
                    type: string
                    description: 'The uuid of the target AirInterface, for which the interfaceNames shall be computed'
                  function-input:
                    type: object
                    description: >
                      'Additional formatting input.
                      Currently not used'
                  function-parameters:
                    type: object
                    description: >
                      'Parameters to configure the function.
                      Currently not used.'
              - description: 'LtpStructureAndAugment'
                type: object
                properties:
                  control-construct:
                    type: object
                    properties:
                      logical-termination-point:
                        type: array
                        x-key: uuid
                        items:
                          type: object
                          properties:
                            uuid:
                              type: string
                            ltp-augment-1-0:ltp-augment-pac:
                              type: object
                              properties:
                                external-label:
                                  type: string
                                  description: 'linkEndpointId - linkId+[AB]'
                                  example: '102550001A'
                  uuid:
                    type: string
                    description: 'The uuid of the target AirInterface, for which the interfaceNames shall be computed'
                  function-input:
                    type: object
                    description: >
                      'Additional formatting input.
                      Currently not used'
                  function-parameters:
                    type: object
                    description: >
                      'Parameters to configure the function.
                      Currently not used.'
    output:
      success:
        description: 'AirInterfaceNames provided'
        content:
          application/json:
            schema:
              type: object
              properties:
                link-endpoint-id:
                  type: string
                  description: >
                    'The linkEndpointId - linkId + [AB]
                    from {$input#raw-control-construct/logical-termination-point/ltp-augment-1-0:ltp-augment-pac/external-label}
                    where {$input#raw-control-construct/logical-termination-point/uuid} == {$input#uuid}'
                link-id:
                  type: string
                  description: >
                    'The linkId
                    from {$input#raw-control-construct/logical-termination-point/ltp-augment-1-0:ltp-augment-pac/external-label.substring(0,9)}
                    where {$input#raw-control-construct/logical-termination-point/uuid} == {$input#uuid}'
      error:
        description: 'just for preventing an error in VSCode'
        # todo: description potentially to be deleted; behavior in case of errors to be described

paths:
  /:
    description: 'no rest path provided by this module'
