spring.application.name=kafkastream
server.port=8085

# Kafka Bootstrap Server
spring.kafka.streams.bootstrap-servers=localhost:9092

# Default Serdes (optional if you use custom ones manually)
spring.kafka.streams.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.default.value.serde=com.start.kafkastreams.JsonNodeSerde

# Optional: Disable auto-start (if you're also using Spring-managed beans)
spring.kafka.streams.auto-startup=false
