@startuml Workflow for Specifying Applications
:Define ApplicationOwner;
:Describe Purpose of the Application;
:Clarify Funding;
:Choose ApplicationName;
:Request for ApplicationRepository;
:Complete ServiceList;
:Complete ProfileList;
:Complete ProfileInstanceList;
:Complete ForwardingList;
:Design CONFIGfile;
:Design OpenApiSpecification;
:Script TestCases;
:Review;
:Freeze Specification;
:Publish Specification;
@enduml