@startuml Workflow for Specifying Applications
:<color:Green>Define ApplicationOwner</color>;
:<color:Green>Describe Purpose of the Application</color>;
:<color:Green>Clarify Funding</color>;
:<color:Green>Choose ApplicationName</color>;
:<color:Green>Request for ApplicationRepository</color>;
:<color:Green>Complete ServiceList</color>;
:<color:Green>Complete ProfileList</color>;
:<color:Green>Complete ProfileInstanceList</color>;
:Complete ForwardingList;
:Design CONFIGfile;
:Design OpenApiSpecification;
:Script TestCases;
:Review;
:Freeze Specification;
:Publish Specification;
@enduml