openapi: 3.0.0
info:
  title: p1DiscardIrrelevantPmRecords
  version: 1.0.0

x-javascript-interface:
  p1DiscardIrrelevantPmRecords: 
    summary: 'This function provides the EthContainer names looked up from LtpAugment information'
    input:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
            - historical-performance-data-list
            - parameters
            properties:
              historical-performance-data-list:
                type: array
                items:
                  type: object
                  required:
                    - granularity-period
                    - period-end-time
                    - performance-data
                  properties:
                    granularity-period:
                      type: string
                      description: 'Indicates the granularity of the PM record'
                    period-end-time:
                      type: string
                      description: 'The timestamp of this PM data record'
                    performance-data:
                      type: object
                      description: 'The object containing actual PM data'
                description: 'The list of historical PM records, that shall be filtered'
              most-recent-period-end-time:
                type: string
                description: 'The (optional) timestamp for filtering 15min PM records. If not provided any 15min records are treated as newer'
              most-recent-period-end-time-24:
                type: string
                description: 'The (optional) timestamp for filtering 24h PM records. If not provided a 24h record is treated as newer'
              parameters:
                type: object
                description: 'Parameters to configure this function.'
                properties:
                  relevant-granularities:
                    type: string
                    description: >
                      'This parameter is a regex pattern, that indicates which granularity periods are relevant. Filled
                      from stringProfile parameters.historicalPmDataGranularitiesToBeKept.'
    output:
      success:
        description: 'Filtered historicalPerformanceDataList provided'
        content:
          application/json:
            schema:
              type: object
              required:
                - historical-performance-data-list
              properties:
                historical-performance-data-list:
                  type: array
                  description: >
                    'The output historicalPerformanceDataList only contains relevant records; irrelevant records are discarded. A record is considered irrelevant
                     IF {$input#historical-performance-data-list/granularity-period} does not match the pattern {$input#parameters.relevant-granularities}

                     In case the record has the expected granularity, the timestamp filter is applied. Discard the record,
                     - IF ({$input#historical-performance-data-list/granularity-period} indicates 15min) AND ({$input#historical-performance-data-list/granularity-period} is not newer than {$input#most-recent-period-end-time})
                     - IF ({$input#historical-performance-data-list/granularity-period} indicates 24h) AND ({$input#historical-performance-data-list/granularity-period} is not newer than {$input#most-recent-period-end-time-24})
                     IF a record with desired granularity is encountered, but the related filter timestamp was not provided as input, the record is to be considered as newer (i.e. kept)
                      
                     IF no records remain, an empty list is returned.'
                  items:
                    type: object
                    properties:
                      granularity-period:
                        type: string
                      period-end-time:
                        type: string
                      performance-data:
                        type: object
      error:
        description: 'Filtered historicalPerformanceDataList could not be provided'
        content:
          application/json:
            schema:
              type: string
              enum:
                - 'Input object incomplete or invalid'
                - 'Input parameters missing or invalid'
                - 'General processing error during filtering'
    processing:
      description: 'No requests or calls to other Functions'


paths:
  /:
    description: 'no rest path provided by this module'