servers:

  operation-servers:
    own-oam:
      basic:
        - operation-name: /v1/register-yourself
          uuid: ro-2-1-2-op-s-bm-000
        - operation-name: /v1/embed-yourself
          uuid: ro-2-1-2-op-s-bm-001
        - operation-name: /v1/redirect-service-request-information
          uuid: ro-2-1-2-op-s-bm-002
        - operation-name: /v1/redirect-oam-request-information
          uuid: ro-2-1-2-op-s-bm-003
        - operation-name: /v1/end-subscription
          uuid: ro-2-1-2-op-s-bm-004
        - operation-name: /v1/inquire-oam-request-approvals
          uuid: ro-2-1-2-op-s-bm-005
        - operation-name: /v1/update-client
          uuid: ro-2-1-2-op-s-bm-007
        - operation-name: /v1/list-ltps-and-fcs
          uuid: ro-2-1-2-op-s-bm-008
        - operation-name: /v1/redirect-topology-change-information
          uuid: ro-2-1-2-op-s-bm-009
        - operation-name: /v1/update-operation-key
          uuid: ro-2-1-2-op-s-bm-010
        - operation-name: /v1/update-operation-client
          uuid: ro-2-1-2-op-s-bm-011
        - operation-name: /v1/inquire-basic-auth-approvals
          uuid: ro-2-1-2-op-s-bm-012
        - operation-name: /v1/dispose-remainders-of-deregistered-application
          uuid: ro-2-1-2-op-s-bm-013
        - operation-name: /v1/inform-about-preceding-release
          uuid: ro-2-1-2-op-s-bm-014
        - operation-name: /v1/update-client-of-subsequent-release
          uuid: ro-2-1-2-op-s-bm-015
      individual:
        - operation-name: /v1/bequeath-your-data-and-die
          uuid: ro-2-1-2-op-s-im-000
    service:
      basic:
        - operation-name: /v1/start-application-in-generic-representation
          uuid: ro-2-1-2-op-s-bs-000
        - operation-name: /v1/inform-about-application
          uuid: ro-2-1-2-op-s-bs-001
        - operation-name: /v1/inform-about-application-in-generic-representation
          uuid: ro-2-1-2-op-s-bs-002
        - operation-name: /v1/inform-about-release-history
          uuid: ro-2-1-2-op-s-bs-003
        - operation-name: /v1/inform-about-release-history-in-generic-representation
          uuid: ro-2-1-2-op-s-bs-004
        - operation-name: /docs
          uuid: ro-2-1-2-op-s-bs-005
      individual:
  http-server:
    own-application-name:
    own-release-number:
    uuid: ro-2-1-2-http-s-000
  tcp-server:
    - description: Without TLS layer
      local-protocol: http
      own-ip-address: 127.0.0.1
      own-tcp-port:
      uuid: ro-2-1-2-tcp-s-000


clients:

  - http-client:
      application-name: ElasticSearch
      release-number: 1.0.0
      uuid: ro-2-1-2-http-c-es-1-0-0-000
    tcp-client:
      remote-protocol: http
      ip-address: 127.0.0.1
      tcp-port: 3015
      uuid: ro-2-1-2-tcp-c-es-1-0-0-000
    elasticsearch-client:
      uuid: ro-2-1-2-es-c-es-1-0-0-000
      index-alias:

  - http-client:
      application-name: OldRelease
      release-number:
      uuid: ro-2-1-2-http-c-or-2-1-1-000
    tcp-client:
      remote-protocol: http
      ip-address: 127.0.0.1
      tcp-port:
      uuid: ro-2-1-2-tcp-c-or-2-1-1-000
    operation-clients:
      own-oam:
        basic:
          - operation-name: /v1/bequeath-your-data-and-die
            uuid: ro-2-1-2-op-c-bm-or-2-1-1-000
        individual:
      service:
        basic:
        individual:

  - http-client:
      application-name: NewRelease
      release-number:
      uuid: ro-2-1-2-http-c-nr-2-1-2-000
    tcp-client:
      remote-protocol: http
      ip-address: 127.0.0.1
      tcp-port:
      uuid: ro-2-1-2-tcp-c-nr-2-1-2-000
    operation-clients:
      own-oam:
        basic:
        individual:
      service:
        basic:
        individual:

  - http-client:
      application-name: RegistryOffice
      release-number: 2.1.0
      uuid: ro-2-1-2-http-c-ro-2-1-2-000
    tcp-client:
      remote-protocol: http
      ip-address: 127.0.0.1
      tcp-port: 3031
      uuid: ro-2-1-2-tcp-c-ro-2-1-2-000
    operation-clients:
      own-oam:
        basic:
          - operation-name: /v2/register-application
            uuid: ro-2-1-2-op-c-bm-ro-2-1-2-000
          - operation-name: /v1/relay-server-replacement
            uuid: ro-2-1-2-op-c-bm-ro-2-1-2-001
          - operation-name: /v1/deregister-application
            uuid: ro-2-1-2-op-c-bm-ro-2-1-2-002
          - operation-name: /v1/relay-operation-update
            uuid: ro-2-1-2-op-c-bm-ro-2-1-2-003
        individual:
      service:
        basic:
        individual:

  - http-client:
      application-name: TypeApprovalRegister
      release-number: 2.1.0
      uuid: ro-2-1-2-http-c-tar-2-1-2-000
    tcp-client:
      remote-protocol: http
      ip-address: 127.0.0.1
      tcp-port: 3032
      uuid: ro-2-1-2-tcp-c-tar-2-1-2-000
    operation-clients:
      own-oam:
        basic:
        individual:
      service:
        basic:
        individual:

  - http-client:
      application-name: ExecutionAndTraceLog
      release-number: 2.1.0
      uuid: ro-2-1-2-http-c-eatl-2-1-2-000
    tcp-client:
      remote-protocol: http
      ip-address: 127.0.0.1
      tcp-port: 3033
      uuid: ro-2-1-2-tcp-c-eatl-2-1-2-000
    operation-clients:
      own-oam:
        basic:
        individual:
      service:
        basic:
          - operation-name: /v1/record-service-request
            uuid: ro-2-1-2-op-c-bs-eatl-2-1-2-000
        individual:

  - http-client:
      application-name: OamLog
      release-number: 2.1.0
      uuid: ro-2-1-2-http-c-ol-2-1-2-000
    tcp-client:
      remote-protocol: http
      ip-address: 127.0.0.1
      tcp-port: 3034
      uuid: ro-2-1-2-tcp-c-ol-2-1-2-000
    operation-clients:
      own-oam:
        basic:
        individual:
      service:
        basic:
          - operation-name: /v1/record-oam-request
            uuid: ro-2-1-2-op-c-bs-ol-2-1-2-000
        individual:

  - http-client:
      application-name: AccessAdministration
      release-number: 2.1.0
      uuid: ro-2-1-2-http-c-aa-2-1-2-000
    tcp-client:
      remote-protocol: http
      ip-address: 127.0.0.1
      tcp-port: 3035
      uuid: ro-2-1-2-tcp-c-aa-2-1-2-000
    operation-clients:
      own-oam:
        basic:
        individual:
      service:
        basic:
          - operation-name: /v1/approve-basic-auth-request
            uuid: ro-2-1-2-op-c-bs-aa-2-1-2-000
        individual:

  - http-client:
      application-name: ApplicationLayerTopology
      release-number: 2.1.0
      uuid: ro-2-1-2-http-c-alt-2-1-2-000
    tcp-client:
      remote-protocol: http
      ip-address: 127.0.0.1
      tcp-port: 3036
      uuid: ro-2-1-2-tcp-c-alt-2-1-2-000
    operation-clients:
      own-oam:
        basic:
          - operation-name: /v1/update-all-ltps-and-fcs
            uuid: ro-2-1-2-op-c-bm-alt-2-1-2-000
          - operation-name: /v1/update-ltp
            uuid: ro-2-1-2-op-c-bm-alt-2-1-2-001
          - operation-name: /v1/delete-ltp-and-dependents
            uuid: ro-2-1-2-op-c-bm-alt-2-1-2-002
          - operation-name: /v1/update-fc
            uuid: ro-2-1-2-op-c-bm-alt-2-1-2-003
          - operation-name: /v1/update-fc-port
            uuid: ro-2-1-2-op-c-bm-alt-2-1-2-004
          - operation-name: /v1/delete-fc-port
            uuid: ro-2-1-2-op-c-bm-alt-2-1-2-005
        individual:
      service:
        basic:
        individual:

  - http-client:
      application-name: OperationKeyManagement
      release-number: 2.1.0
      uuid: ro-2-1-2-http-c-okm-2-1-2-000
    tcp-client:
      remote-protocol: http
      ip-address: 127.0.0.1
      tcp-port: 3037
      uuid: ro-2-1-2-tcp-c-okm-2-1-2-000
    operation-clients:
      own-oam:
        basic:
        individual:
      service:
        basic:
        individual:
