@startuml p1LoadParameters
skinparam responseMessageBelowArrow true

title
  p1LoadParameters
end title

participant "requestor\n" as p1RMWDI #LightGrey
participant "p1LoadParameters\n" as p1LP #LightCyan
participant "configFile\n" as p1CF #LightCyan

activate p1RMWDI #LightGrey

p1RMWDI -> p1LP : {functionName}
activate p1LP #LightCyan

  note right p1LP
    load the application's
    CC from configFile
  end note

  p1LP -> p1CF
  p1LP <-- p1CF

  note right p1LP
    Find uuid of FunctionProfile
    instance with functionName
  end note


  loop
    note right p1LP
      Load instance of FunctionProfile from
      the internal copy of the configFile and
      translate into internal parameters format
    end note
    p1LP -> p1LP

    note right p1LP
      Read uuids of SubFunctions
    end note
  end

p1RMWDI <-- p1LP : {{parameters},\n{configFile}}
deactivate p1LP
