openapi: 3.0.0
info:
  title: p1ComputeAirInterfacePhysicalLag
  version: 1.0.0

x-javascript-interface:
  p1ComputeAirInterfacePhysicalLag: 
    summary: 'This function provides the LinkAggregation identifiers looked up from LtpAugment information'
    input:
      required: true
      content:
        application/json:
          schema:
            oneOf:
              - description: 'data reference'
                type: object
                properties:
                  _control-construct:
                    type: object
                    description: >
                      'The reference to the ControlConstruct object on which lookup shall be executed.
                      The data follows ONF schema. Option LtpStructureAndAugment lists the relevant attributes and subclasses.'
                  uuid:
                    type: string
                    description: 'The uuid of the target AirInterface, for which the LAG information shall be computed'
                  function-input:
                    type: object
                    description: >
                      'Additional formatting input.
                      Currently not used'
                  function-parameters:
                    type: object
                    description: >
                      'Parameters to configure the function.
                      Currently not used.'
              - description: 'LtpStructureAndAugment'
                type: object
                properties:
                  control-construct:
                    type: object
                    properties:
                      logical-termination-point:
                        type: array
                        x-key: uuid
                        items:
                          type: object
                          properties:
                            uuid:
                              type: string
                            client-ltp:
                              type: array
                              description: 'The client-LTPs array of the current LTP'
                              items:
                                type: string
                            server-ltp:
                              type: array
                              description: 'The server-LTPs of the current LTP'
                              items:
                                type: string
                            layer-protocol:
                              type: array
                              items:
                                type: object
                                properties:
                                  local-id:
                                    type: string
                                    description: 'The local-id of the current LTP/layer-protocol'
                                  layer-protocol-name:
                                    type: string
                                    description: 'The layer-protocol-name of the current LTP/layer-protocol'
                            ltp-augment-1-0:ltp-augment-pac:
                              type: object
                              properties:
                                external-label:
                                  type: string
                                original-ltp-name:
                                  type: string
                  uuid:
                    type: string
                    description: 'The uuid of the target AirInterface, for which the LAG information shall be computed'
                  function-input:
                    type: object
                    description: >
                      'Additional formatting input.
                      Currently not used'
                  function-parameters:
                    type: object
                    description: >
                      'Parameters to configure the function.
                      Currently not used.'
    output:
      success:
        description: 'AirInterface Physical LAG provided'
        content:
          application/json:
            schema:
              description: >
                'This service determines the Link aggregation information for all air-interface instances of the device from the request.body#ltp-structure-and-augment.
                Therefore it first iterates over the all {$input#control-construct/logical-termination-point} array items and computes the LAG lookup list if the
                layer-protocol-name found in the ltp information belongs to the {$input#uuid} indicates AIR_LAYER.
                The uuid for the retrieval from ltp-augment information is not the one of the AirInterface itself, but has to be determined by stepping through the hierarchy of LTPs on top of the AirInterface
                as follows:
                  ClientLtp OF AirInterfaceUuid = ClientStructureUuid
                  ClientLtp OF ClientStructureUuid = ClientEthernetContainerUuid
                  ServerLtp OF ClientEthernetContainerUuid = LIST-OF ServingStructureUuid

                  FOR EACH ServingStructureUuid in LIST-OF ServingStructureUuid:
                  ServerLtp OF ServingStructureUuid = Wire/AirInterfaceUuid
                  
                  Result = List-of-Wire/AirInterfaceUuid
                  
                After this lookup list has been compiled, the LAG information can be compiled by reading the relevant attributes from the LTP augments beloning to the uuids from the lookup list.
                For each uuid in List-of-Wire/AirInterfaceUuid:
                If (uuid == AIR_LAYER uuid) then linkId = externalLabel.substring(0,9),
                else if (uuid == WIRE_LAYER uuid) then interfaceName = originalLtp'
              type: object
              properties:
                link-aggregation-identifiers:
                  type: array
                  items:
                    oneOf:
                      - description: 'AirInterface'
                        type: object
                        required:
                          - link-id
                        properties:
                          link-id:
                            type: string
                            example: '513550010'
                            description: >
                              'The link-ID for the current AirInterface uuid from List-of-Wire/AirInterfaceUuids to be obtained by extracting the substring constituted by the 9 first characters
                              from {$input#control-construct/logical-termination-point[currentUuid]/ltp-augment-1-0:ltp-augment-pac/external-label}'
                      - description: 'WireInterface'
                        type: object
                        required:
                          - interface-name
                        properties:
                          interface-name:
                            type: string
                            description: >
                              'Interface name for the current WireInterface uuid from List-of-Wire/InterfaceUuids
                              from {$input#control-construct/logical-termination-point[currentUuid]/ltp-augment-1-0:ltp-augment-pac/original-ltp-name}'
      error:
        description: 'just for preventing an error in VSCode'
        # todo: description potentially to be deleted; behavior in case of errors to be described

paths:
  /:
    description: 'no rest path provided by this module'
